name: Version
description: Get the next version based on the latest tag

author: "CDQ AG"
branding:
  icon: 'arrow-up-circle'
  color: 'red'

inputs:
  pep440:
    description: 'The next version in PEP440 format'
    default: 'false'

outputs:
  current-version:
    description: 'The current version'
    value: ${{ steps.set.outputs.current-version }}
  new-major-version:
    description: 'The next major version'
    value: ${{ steps.set.outputs.new-major-version }}
  new-version:
    description: 'The next version'
    value: ${{ steps.set.outputs.new-version }}

runs:
  using: 'composite'
  steps:
    - name: Check Prerequisites
      shell: bash
      run: |
        if [[ -z "$BRANCH_NAME" ]]; then
          echo "This action requires env.BRANCH_NAME to be set. Please either use cdqag/action-init, or manualy set env.BRANCH_NAME."
          exit 1
        fi

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: ${{ env.BRANCH_NAME }}
        noVersionBumpBehavior: patch

    - name: Set Outputs
      id: set
      shell: bash
      env:
        PEP440: ${{ inputs.pep440 }}
        NEXT: ${{ steps.semver.outputs.nextStrict }}
      run: |
        echo "CURRENT_VERSION=${{ steps.semver.outputs.current }}" >> "$GITHUB_ENV"
        echo "current-version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

        echo "NEW_MAJOR_VERSION=${{ steps.semver.outputs.nextMajorStrict }}" >> "$GITHUB_ENV"
        echo "new-major-version=$NEW_MAJOR_VERSION" >> "$GITHUB_OUTPUT"

        if [[ "$BRANCH_NAME" != "master" ]]; then
          NEXT="$NEXT-${GITHUB_SHA:0:8}"
        fi
        
        if [[ "$PEP440" == "true" ]]; then
          NEXT=$(echo "$NEXT" | sed 's/-/+/g')
        fi
        echo "NEW_VERSION=$NEXT" >> "$GITHUB_ENV"
        echo "new-version=$NEXT" >> "$GITHUB_OUTPUT"
