name: Version
description: Get the next version based on the latest tag

author: "CDQ AG"
branding:
  icon: 'arrow-up-circle'
  color: 'red'

inputs:
  branch-name:
    description: The branch name
    required: true
    default: ${{ env.BRANCH_NAME }}

outputs:
  current:
    description: The current version
    value: ${{ steps.set.outputs.current }}

  next:
    description: Next (new) version
    value: ${{ steps.set.outputs.next }}

  nextPep440:
    description: Next (new) version (PEP440 compliant)
    value: ${{ steps.set.outputs.nextPep440 }}

  nextMajor:
    description: Next (new) major version
    value: ${{ steps.set.outputs.nextMajor }}

runs:
  using: 'composite'
  steps:
    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: ${{ inputs.branch-name }}
        noVersionBumpBehavior: patch

    - name: Set Outputs
      id: set
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch-name }}
        NEXT: ${{ steps.semver.outputs.nextStrict }}
      run: |
        echo "current=${{ steps.semver.outputs.current }}" >> "$GITHUB_OUTPUT"
        echo "nextMajor=${{ steps.semver.outputs.nextMajorStrict }}" >> "$GITHUB_OUTPUT"

        if [[ "$BRANCH_NAME" != "master" ]]; then
          NEXT="$NEXT-${GITHUB_SHA:0:8}"
        fi
        echo "next=$NEXT" >> "$GITHUB_OUTPUT"

        NEXT_PEP440=$(echo "$NEXT" | sed 's/-/+/g')
        echo "nextPep440=$NEXT_PEP440" >> "$GITHUB_OUTPUT"
