name: Update Major Tag

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
  release:
    types:
      - released
      - edited

jobs:
  update-majorver:
    runs-on: hosted-runner
    steps:
      - uses: cdqag/update-majorver@v1
