name: Update Major Tag

on:
  release:
    types:
      - published
      - released
      - edited
      - created

jobs:
  update-majorver:
    runs-on: hosted-runner
    steps:
      - uses: cdqag/update-majorver@v1
